#!/usr/bin/env node
// quilt-atlas builder — zero-dep, runs locally or in Actions.
// Maps the SuperInstance account: inventory, families, CI coverage,
// recent motion. Writes atlas.json + regenerates the README block
// between the ATLAS markers. Honest gaps stay visible (no fabrication).
import { writeFileSync, readFileSync } from 'node:fs';

const TOKEN = process.env.GITHUB_TOKEN || '';
const OWNER = 'SuperInstance';
const H = {
  Authorization: `token ${TOKEN}`,
  Accept: 'application/vnd.github+json',
  'User-Agent': 'quilt-atlas-builder',
};
async function api(url) {
  const r = await fetch(url, { headers: H });
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return r.json();
}

const repos = [];
for (let p = 1; p <= 40; p++) {
  const b = await api(`https://api.github.com/users/${OWNER}/repos?per_page=100&page=${p}`);
  if (!Array.isArray(b) || b.length === 0) break;
  repos.push(...b);
  if (b.length < 100) break;
}

const FAMILIES = [
  ['jev',    /(^|[-_])jev([-_]|$)|jev-|-jev/],
  ['latent', /jepa|latent|embod/],
  ['moth',   /moth|quantum|pong-quilt/],
  ['qthe',   /qthe|canon/],
  ['quilt',  /quilt/],
  ['fleet',  /fleet|seeds|crab|qthe\b/],
];
function familyOf(name) {
  for (const [f, re] of FAMILIES) if (re.test(name)) return f;
  return 'other';
}
// precedence: jev > latent > moth > qthe > quilt > fleet > other
function classify(name) {
  if (/jev/.test(name)) return 'jev';
  if (/jepa|latent/.test(name)) return 'latent';
  if (/moth|quantum/.test(name)) return 'moth';
  if (/qthe|canon/.test(name)) return 'qthe';
  if (/quilt/.test(name)) return 'quilt';
  if (/fleet|seeds|crab/.test(name)) return 'fleet';
  return 'other';
}

const sorted = [...repos].sort((a, b) => (a.pushed_at < b.pushed_at ? 1 : -1));
const TOPN = 24;
const top = sorted.slice(0, TOPN);

// CI coverage on the top slice (cheap: contents API on .github/workflows)
const coverage = [];
for (const r of top) {
  let wf = [];
  try {
    const c = await api(`https://api.github.com/repos/${OWNER}/${r.name}/contents/.github/workflows`);
    if (Array.isArray(c)) wf = c.map((x) => x.name);
  } catch { /* 404: no workflows dir — honest gap */ }
  coverage.push({ repo: r.name, workflows: wf, pushed_at: r.pushed_at, size_kb: r.size });
}

const byFamily = {};
for (const r of repos) {
  const f = classify(r.name);
  (byFamily[f] ||= []).push(r.name);
}

const atlas = {
  generated_at_utc: new Date().toISOString(),
  account: OWNER,
  total_repos: repos.length,
  families: Object.fromEntries(Object.entries(byFamily).map(([k, v]) => [k, v.length])),
  family_members: byFamily,
  top_motion: coverage,
  notes: [
    'families are name-classified, precedence jev>latent>moth>qthe>quilt>fleet; "other" is honest residue, not failure',
    'CI coverage is measured only on the top_motion slice (API economy); absence elsewhere is UNMEASURED, not zero',
    'hard cap 40 pages x 100 = 4000; if total_repos == 4000 the account outgrew the map and the true count is unknown-by-this-run (raise the cap next run)',
  ],
};
writeFileSync('atlas.json', JSON.stringify(atlas, null, 2) + '\n');

const table = coverage
  .map((c) => `| ${c.repo} | ${c.workflows.length ? c.workflows.join(', ') : '— none —'} | ${c.pushed_at.slice(0, 16).replace('T', ' ')} |`)
  .join('\n');
const famLine = Object.entries(atlas.families)
  .sort((a, b) => b[1] - a[1])
  .map(([k, v]) => `${k}=${v}`)
  .join(' · ');

const block = `<!-- ATLAS:BEGIN (generated by scripts/build_atlas.mjs — do not hand-edit inside markers) -->
**${atlas.total_repos} repos** · families: ${famLine} · generated ${atlas.generated_at_utc}

### Top motion (24 most recently pushed) and their CI

| repo | workflows | last push (UTC) |
|---|---|---|
${table}

Missing rows in the table are below the motion cut — see atlas.json for the full inventory.
<!-- ATLAS:END -->`;

const readmePath = 'README.md';
let readme = readFileSync(readmePath, 'utf8');
readme = /<!-- ATLAS:BEGIN[\s\S]*<!-- ATLAS:END -->/.test(readme)
  ? readme.replace(/<!-- ATLAS:BEGIN[\s\S]*<!-- ATLAS:END -->/, block)
  : readme + '\n' + block + '\n';
writeFileSync(readmePath, readme);
console.log(`atlas built: ${atlas.total_repos} repos, ${coverage.length} CI-probed, families ${famLine}`);
